### ISSUE TITLE
Example in docs is not on docs.rs

### ISSUE THREAD

**Issue by tgross35** [mitchmindtree/mdio#1]
Hey @mitchmindtree It looks like the example you added here https://github.com/mitchmindtree/mdio/blob/master/src/bb.rs#L27-L47 are not available on docs.rs https://docs.rs/mdio/latest/mdio/bb/index.html

From https://docs.rs/crate/mdio/latest/source/src/bb.rs it looks like maybe they just didn't get updated, or maybe there was a build failure. Would you be able to publish the latest versions of this repo?

Thank you!

**Comment by mitchmindtree** [comment]
Done!

**Comment by tgross35** [comment]
Thank you for the super quick action!
